### PR TITLE
Avoid parameter spamming in output.

### PR DESCRIPTION
**Pull request by atgeirr**
This is done by using the base class model_param_ and avoid recreating it.

### CODE REVIEW

**Comment by GitPaean** [comment]
I am still seeing something like follows, which is really surprising to me. 
```
relax_max not found. Using default value '0.5'.
max_iter found at /, value is '125'.
min_iter not found. Using default value '1'.
relax_type not found. Using default value 'dampen'.
```
Please help to confirm with what is the case on your side.

**Comment by atgeirr** [comment]
I still have that. So parameter spamming is reduced but not eliminated. I'll see if I can fully eliminate it, so don't merge this just yet.

**Comment by atgeirr** [comment]
It turns out this was very easy to fix, I have pushed an update. Thanks for noticing.

**Comment by GitPaean** [comment]
Looks good. Thanks for fixing. Merging.

**Pull request merged**
