### PR TITLE
hack fix for opm-core ECL changes

### PR DESCRIPTION
**Pull request by akva2**
Not meant as a real fix just pointing out the problem.

### CODE REVIEW

**Comment by bska** [comment]
I don't think this is needed anymore.  The original API was restored in commit OPM/opm-core@2b9b098 (PR OPM/opm-core#698).  I suppose this could be closed?

**Comment by akva2** [comment]
yeah. (sorry for not closing but inconvenient to do so atm).

**Comment by bska** [comment]
> inconvenient to [close PR] atm

Want me to do it for you?

**Comment by akva2** [comment]
yes please.

**Comment by bska** [comment]
>>> inconvenient to [close PR] atm
>>
>> Want me to do it for you?
>
> yes please.

Very well.  I'm closing at your request.

**Pull request closed without merging**
