### PR TITLE
Start refactor fully implicit polymer solver

### PR DESCRIPTION
**Pull request by atgeirr**
This PR requires OPM/opm-autodiff#381, and should be discussed there.

Edit: corrected link.

### CODE REVIEW

**Comment by qilicun** [comment]
Looks good，I will do some tests. Thanks!

**Comment by GitPaean** [comment]
Small typo on the comment.  I think you mean `This PR requires OPM/opm-autodiff#381` instead of opm-core.

**Comment by atgeirr** [comment]
True, thanks for noticing! Will edit.

**Comment by GitPaean** [comment]
It produces identical residual output log. Well done in reproducing the previous results. I think the small difference from yesterday is due to the different computers we are using.

**Comment by GitPaean** [comment]
The results look very good. The problem that I saw the discrepancy with new `getConvergence` in the results looks like fixed in OPM/opm-autodiff#382, which is related to the calculation of `well_flux_residual`.

**Pull request merged**
