### PR TITLE
Updates FIBOPOLYMER simulator based on flow simulator.

### PR DESCRIPTION
**Pull request by qilicun**
Since several months' changes of opm-autodiff, this polymer simulator can get the same results with flow simulator, this means the black oil part changes a lot and some of them are not applied to this fully implicit three-phase-polymer simulator, and which is very hard to debug! So this PR is a re-written basically based on latest flow simulator. Cause now flow is the simulator name, we should also rename sim_poly_fibo_ad to flow_polymer.
A test case is done, both for blackoil and polymer, the results match eclipse very well.

### CODE REVIEW

**Comment by qilicun** [comment]
Sorry, will solve the conflicts.

**Comment by atgeirr** [comment]
That is good! I know it is hard to keep these codes in sync, but with this we will have a good starting point for a refactoring to make it a lot simpler.

**Comment by qilicun** [comment]
For my local test, I can't see the conflicts, @atgeirr Would you mind firing off a merge test?

**Comment by qilicun** [comment]
Here is a results comparison with eclipse for polymer simulator.

test

**Comment by atgeirr** [comment]
> Here is a results comparison with eclipse for polymer simulator.

That looks very nice, what is the base case?

> For my local test, I can't see the conflicts, @atgeirr Would you mind firing off a merge test?

OK.

**Comment by qilicun** [comment]
>That looks very nice, what is the base case?

This a case that I work with Kai for a long time, basically a 2D case. But meanwhile, we want to setup a polymer test suits for regression test to avoid the effects that caused by any changes of the other part of OPM.

**Comment by GitPaean** [comment]
CONFLICT location. 

--- a/opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver_impl.hpp
+++ b/opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver_impl.hpp
@@@ -2173,10 -2394,10 +2398,15 @@@ namespace detail 
              const int num_blocks = p.numBlocks();
              std::vector<ADB::M> jacs(num_blocks);
              for (int block = 0; block < num_blocks; ++block) {
-                 jacs[block] = dpm_diag * p.derivative()[block];
+                 fastSparseProduct(dpm_diag, p.derivative()[block], jacs[block]);
              }
++<<<<<<< HEAD
 +            return ADB::function(std::move(pm), std::move(jacs));
 +         } else {
++=======
+             return ADB::function(pm, jacs);
+         } else {
++>>>>>>> 718d1cb0b1a071c2a75d9efd60325b7a9211294f
              return ADB::constant(V::Constant(n, 1.0), p.blockPattern());
          }
      }

**Comment by qilicun** [comment]
The big green button comes back!

**Comment by GitPaean** [comment]
After updating everything 
```
CMake Error at cmake/Modules/OpmSatellites.cmake:59 (add_executable):
  Cannot find source file:

    /home/kaib/OPM/build/opm-polymer/examples/flow_polymer.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/Modules/OpmLibMain.cmake:223 (opm_compile_satellites)
  CMakeLists.txt:69 (include)
```

**Comment by GitPaean** [comment]
I met one small problem in getting convergent during one time step.  Disabling the relaxation treatment or adjusting the relaxation parameters can make the running go through. The result from our current benchmark case agrees well wit the ECL result. 

To me the PR is ready to merge in term of generating desired results.

**Comment by atgeirr** [comment]
Thanks for checking, Kai. I'll merge!

**Pull request merged**
