### PR TITLE
Adding shear-thinning calculation with PLYSHLOG

### PR DESCRIPTION
**Pull request by GitPaean**
This PR addresses the application of shear-thinning effects based on the PLYSHLOG keyword. The commit history tells pretty accurately about the summary of what are included in this PR. 

The development of this PR (began earlier and ended later) is kind of in parallel with the previous re-factoring process, and may mess up with some of efforts of the re-factoring. There are definitely some space for re-factoring, please suggest whatever is necessary. I think it might be the efficient way to improve the code by creating a PR here.

The PR is verified with our current working examples.

### CODE REVIEW

**Comment by atgeirr** [comment]
A few comments from my initial impression:
 - The 2d intersection stuff should be in its own class and file (ideally in a different place, but we can easily move it later if it's in a separate file).
 - The computeShearMultLog() and possibly some of the other property calculations should be moved to the property class(es).
 - It should be possible to re-use the base versions of assemble() and assembleMassBalance(), I'll assist in making this work. We may have to make a few changes to opm-autodiff to support this.

**Comment by GitPaean** [comment]
Thanks for the comments. 

Just moved the `Point2D` class and the function `findIntersection` to a separate file `Point2D.hpp`. The class is under the namespace `Opm::detail`. I am thinking maybe a more specific name can be better in term of avoiding confusing in the future. 

And also moved the function `computeShearMultLog` to class `PolymerProperties`.

**Comment by GitPaean** [comment]
This is PR is updated with the currently re-factored `opm-autodiff` and `opm-polymer`. It is dependent on the unmerged PR OPM/opm-autodiff#406 and OPM/opm-polymer#131. Thanks for the great re-factoring efforts from @atgeirr .

**Comment by qilicun** [comment]
Thanks for all your effort, I just have one comment. That is can we just have one`has_polyshlog_`? Because basically polymer shear thinning-thickning is just a multiplier, we can set it to 1 by default, whether the deck has keyword `PLYSHLOG` or not, we can do the same procedure. I hope this can improve the readability.

**Comment by GitPaean** [comment]
Yes. The point is that when we need to handle shear-thinning, we have to go through some more processes, and not very small. We want to avoid these extra processes when we do not have shear-thinning involved. And also, the processes with `PLYSHLOG` and `PLYSHEAR` and 'SHRATE` are a little different, probably we can introduce one `has_shear` to indicate if we need to handle shear-thinning effects.

**Comment by atgeirr** [comment]
Thanks for the effort, I will merge this now. There are changes we may want, such as discussed by @qilicun above, or further refactoring (getting rid of the custom assemble() method would be nice for example), but that can wait.

**Pull request merged**
