### PR TITLE
adapting to the change in autodiff#408

### PR DESCRIPTION
**Pull request by GitPaean**
This is a companion PR of OPM/opm-autodiff#408. Please do not merge before PR OPM/opm-autodiff#408 got merged. 

The results are verified with our working examples (small cases) with small changes in the residual history.

### CODE REVIEW

**Comment by bska** [comment]
> Please do not merge before PR OPM/opm-autodiff#408 got merged.

Must the two be merged in companion?

**Comment by GitPaean** [comment]
Yes, since the function interface are changed for `fluidViscosity` and `fluidDensity`. Let me test it a little bit again and let you know if everything is still good with this PR and its companion PR in autodiff.

**Comment by GitPaean** [comment]
This PR is still working well with its companion PR in autodiff for my working examples.

**Comment by bska** [comment]
> This PR is still working well with its companion PR in autodiff for my working examples.

Thanks for testing.  I'll merge this and the companion into their respective master branches.

**Pull request merged**
